// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iahzgkqwyuqcdnycutdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhaHpna3F3eXVxY2RueWN1dGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4OTU1NTgsImV4cCI6MjA0OTQ3MTU1OH0.x4pElR9WOOSxoCcxLPNVmQF5ZcWlYSVHFkXLMtjBAdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);